// var gameplayTips = [ 
//     'Your shots do more damage if they strike the center of an enemy egg',
//     'Your accuracy decreases if you fire while moving, especially with the sniper rifle',
//     'Hold down the Grenade button to throw further',
//     'You can cancel a Grenade throw by pressing the Fire button',
//     'Enable chat in the Options menu (but beware of foul-mouthed louts)',
//     'Shoot gooder to die lesser',
//     'Your health regenerates slowly over time',
//     'Earn Golden Eggs to buy new hats, decals, and gun skins in the store',
//     'Do your homework instead of playing video games',
//     'Listen to your teacher, kids, don’t end up in the gutter',
//     'Switch to your sidearm for close-quarter kills',
//     'Your Shell Shocker friends are important but so are your real-life friends',
//     'Don’t do drugs, they’re for loozers',
//     'You can create private games for your friends and send them a link',
//     'Turn off details in Settings if your framerate is low',
//     'Cast iron skillets fry the best eggs',
//     'Look around when going up ladders',
//     'Not in the middle of the action?  Don’t forget to reload',
//     'The EggK-47 is more accurate at long range if you fire slowly',
//     'Private game owners can boot problem players by clicking on them in the leaderboard',
//     'You can mute and change the names of players by clicking on them in the leaderboard'
// ];

var gameplayTips = [
    "Join the Discord!",
    "lmfaoooo",
    "balls",
    "Girlfriend update coming in 3-5 business days",
    "Fantasize about getting kills not about eggussy",
    "stop poppin pills and start killin shells",
    "did you know legacyshell has a wiki????",
    "but can yuo beat the piper........",
    "fun fact: the playtester on the map editor actually works!",
    "Feeling bad because you just lost your life savings to the Hawk Tuah rugpull? Play some legacyshell to feel better.",
    ":laughathisuser:",
    "Did You know that you can win a sex stamp of choice if u join our discord server\nWtf is a sex stamp",
    "girlfriend hack working 2024 please onplypuppy",
    "Piper's pillar, the hardest for thee, kneel behind his mark til the Piper you see.",
    "Always keep your tools clean... nobody likes a clogged pipe",
    "In legacy shell, aim for the middle of the egg. It’s like hitting the spot — quick, satisfying, and a little bit dirty.",
    "Don't rage because people are better than you, you just suck",
    "Always play like Harrison is watching.",
    "The faster you shoot, the more satisfaction you’ll get. No one likes a slow shooter.",
    "Join Legacy Shell competitions to win eggstra items and skins",
    "The key to survival? Don’t just crack under pressure, crack your opponents first!",
    "Remember that Shell Shockers may be the newer version, but in LegacyShell, we keep things cracking with style",
    "Wait!?!?!?!? Does Onlypuppy have a only fans page??!?!?! ",
    "Touching grass might just give you special powers",
    "press ctrl + w for hax",
    "Fornite isnt as eggciting as shell ever could be ",
    "Well well well, look who broke their shell",
    "fun fact: when you fire the rpegg an the crosshair red you cant shoot but the green crosshair you can shoot",
    ":joe_hm:",
    "Remember to brush your teeth after eating eggs ",
    "please be extra toxic to new players and make them ragequit",
    "No frying, you must cook!",
    "Don’t just shoot—aim for the cracks, the sweet spots, and make em' egg-stra messy!",
    "😭",
    "Why are all the motds just getting increasingly more sus",
    "make this one win that's a good motd puppy is sooo talented",
    "huck tuah",
    "Come on baby, turn off your hack and beat me 10-0😏",
    "git gud",
    "https://discord.gg/GfEJJyj4",
    "💀",
    "If You’re Having Trouble Winning, Try Getting Better At The Game. ",
    "When The Time Of The Winter Comes, Do Not Eat The Yellow Snow. ",
    "Got no friends? Spawn some bots!",
    "daisy, daisy, give me your answer, do. im half crazy all for the love of youuu",
    "What",
    "Did you know that the game shell shockers is a cheap copy of legacy shell",
    "real and based",
    "We will never know",
    "Did u know that statefarm is also a multinational insurance company",
    "Dont get your eggs cracked.... literally"
];

function getRandomGameplayTip() {
    var rndIdx = Math.randomInt(0, gameplayTips.length);
    return gameplayTips[rndIdx];
}