# services/sync server settings

# looking for the distributed config? its now a separate file.

port: 13371

# a discord webhook for all feedback to be sent. leave to "false" to disable feedback
feedback: false 

# set interval in hours between each opportunity to get the 1 hour of vip
nugget_interval: 24 

# makes the errors less revealing of which usernames exist.
# but this is pointless, as you can just send a register request.
# if the user doesnt exist, then there is no way you can sign up with it anyway.
# this is just out of spite, tbh. (hijinks ensue.......)
protect_usernames: false 

#higher is more secure, but will require more processing power - run "npm run bcrypt" to determine the recommended cost
#you should probably leave as is though, because lowering will make it less secure in the event of a breach
#this is the main defense against a breach, so dont mess with it unless you know what you are doing
password_cost_factor: 10

#how long, in minutes, sessions should exist for
session_expiry_time: 180
#how often, in minutes, sessions should be purged
#should NOT be higher than expiry time (above)! you will make some strange stuff happen, i can only imagine! dont!
session_cleanup_interval: 3 

ratelimit: #limit spammy requests
  regular:
    max_count: 10
    reset_interval: 60 #in seconds
    
  sensitive:
    max_count: 5
    reset_interval: 300 #in seconds
    cmds:
      - "validateLogin"
      - "validateLoginViaAuthToken"
      - "validateRegister"
      - "feedback"

  protect_ips: true #md5 hashes ips. this is not a very strong algorithm, so still be careful about sharing info

backups: #backup database
  enabled: true
  interval: 4 #in hours
  keep: 50 #how many backups to keep
  filepath: false #where to store the backups. false to store in the default location