const colors = require('colors');

const logMethods = {
    green: (message) => console.log(message.green),
    red: (message) => console.log(message.red),
    yellow: (message) => console.log(message.yellow),
    blue: (message) => console.log(message.blue),
    cyan: (message) => console.log(message.cyan),
    magenta: (message) => console.log(message.magenta),
    white: (message) => console.log(message.white),
    gray: (message) => console.log(message.gray),
    black: (message) => console.log(message.black),
    pink: (message) => console.log(message.hex('#FFC0CB')),
    orange: (message) => console.log(message.hex('#FFA500')),
    purple: (message) => console.log(message.hex('#800080')),
    brown: (message) => console.log(message.hex('#A52A2A')),
    beige: (message) => console.log(message.hex('#F5F5DC')),

    bgGreen: (message) => console.log(message.bgGreen),
    bgRed: (message) => console.log(message.bgRed),
    bgYellow: (message) => console.log(message.bgYellow),
    bgBlue: (message) => console.log(message.bgBlue),
    bgCyan: (message) => console.log(message.bgCyan),
    bgMagenta: (message) => console.log(message.bgMagenta),
    bgWhite: (message) => console.log(message.bgWhite),
    bgGray: (message) => console.log(message.bgGray),
    bgBlack: (message) => console.log(message.bgBlack),
    bgPink: (message) => console.log(message.bgHex('#FFC0CB')),
    bgOrange: (message) => console.log(message.bgHex('#FFA500')),
    bgPurple: (message) => console.log(message.bgHex('#800080')),
    bgBrown: (message) => console.log(message.bgHex('#A52A2A')),
    bgBeige: (message) => console.log(message.bgHex('#F5F5DC')),

    bold: (message) => console.log(message.bold),
    italic: (message) => console.log(message.italic),
    underline: (message) => console.log(message.underline),
    inverse: (message) => console.log(message.inverse),
    strikethrough: (message) => console.log(message.strikethrough),
    dim: (message) => console.log(message.dim),
    hidden: (message) => console.log(message.hidden),

    success: (message) => console.log(message.green.bold),
    error: (message) => console.log(message.red.bold),
    warning: (message) => console.log(message.yellow.bold),
    info: (message) => console.log(message.blue.bold),
    highlight: (message) => console.log(message.bgYellow.black.bold),
    muted: (message) => console.log(message.gray.italic),
    special: (message) => console.log(message.cyan.underline),
    custom: (message, color) => console.log(message[color]),
    customBg: (message, color) => console.log(message[color]),
};

module.exports = logMethods;
