# config.yaml, yep
client:
  port: 13370
  minify: true #this lags startup of the server by a few seconds, in theory though will reduce lag longer term

services:
  port: 13371

websocket:
  port: 13372