# config.yaml, yep
client:
  sync_server: "ws://localhost:13371" #this is basically the services server. but its not! this is what the client server will internally use to retrieve its configs and shit. in theory the sync server could put in a different services URL entirely! anyway, if the client and services servers are both running on the same machine, you can keep this as localhost.
  this_url: "legacy.onlypuppy7.online" #used in some find and replaces. input the url you want people to access your site via.
  port: 13370

services:
  port: 13371
  feedback: false # a discord webhook for all feedback to be sent. leave to "false" to disable feedback
  protect_usernames: false #makes the errors less revealing of which usernames exist. but this is pointless, as you can just send a register request. if the user doesnt exist, then there is no way you can sign up with it anyway. this is just out of spite, tbh.
  password_cost_factor: 10 #higher is more secure, but will require more processing power - run "npm run bcrypt" to determine the recommended cost
  session_expiry_time: 180 #how long, in minutes, sessions should exist for
  session_cleanup_interval: 3 #how often, in minutes, sessions should be purged (should NOT be higher than expiry time! you will make some strange stuff happen, i can only imagine! dont!)
  ratelimit: #limit spammy requests
    regular:
      max_count: 10
      reset_interval: 60 #in seconds
    sensitive:
      max_count: 5
      reset_interval: 300 #in seconds
      cmds:
        - "validateLogin"
        - "validateLoginViaAuthToken"
        - "validateRegister"
        - "feedback"
    protect_ips: true
  #this is what the other servers will ping this server for
  distributed_configs:
    client:
      servicesURL: "wss://services-legacy.onlypuppy7.online:443"
      minify: true #this lags startup of the server by a few seconds, in theory though will reduce lag longer term for both clients and the server itself
      discordServer: F3Xh5bhXTr # do NOT put anything except the ending id/vanity as the rest is filled in!
      githubURL: "https://github.com/onlypuppy7/LegacyShell/"

game:
  services_server: "ws://localhost:13371"
  auth_key: "AUTH_KEY" #this is given by the owner of the services server, and can be revoked.
  port: 13372

#config for how you want the files to continually run. setup for error notifications on discord!
perpetual:
  client:
    process_cmd: "server-client/run-client.js" #dont touch unless ur sure about it
    #daily restarts, at specified time every day
    dailyrestart_enable: true
    dailyrestart_time: "4:00"
    #logfiles
    logfile_enable: true
    #webhook logging
    webhook_url: "" #empty disables it
    webhook_username: "LegacyShell: Client Server"
    webhook_avatar: "https://cdn.onlypuppy7.online/legacyshell/client.png"
    webhook_ping_user: "" #ENTER THE USER ID. for when there is an error. empty = no ping.
    webhook_ping_role: "" #ENTER THE ROLE ID. for when there is an error. empty = no ping.
  services:
    process_cmd: "server-services/run-services.js" #dont touch unless ur sure about it
    #daily restarts, at specified time every day
    dailyrestart_enable: true
    dailyrestart_time: "4:00"
    #logfiles
    logfile_enable: true
    #webhook logging
    webhook_url: "" #empty disables it
    webhook_username: "LegacyShell: Services Server"
    webhook_avatar: "https://cdn.onlypuppy7.online/legacyshell/services.png"
    webhook_ping_user: "" #ENTER THE USER ID. for when there is an error. empty = no ping.
    webhook_ping_role: "" #ENTER THE ROLE ID. for when there is an error. empty = no ping.
  game:
    process_cmd: "server-game/run-game.js" #dont touch unless ur sure about it
    #daily restarts, at specified time every day
    dailyrestart_enable: true
    dailyrestart_time: "4:00"
    #logfiles
    logfile_enable: true
    #webhook logging
    webhook_url: "" #empty disables it
    webhook_username: "LegacyShell: Game Server"
    webhook_avatar: "https://cdn.onlypuppy7.online/legacyshell/game.png"
    webhook_ping_user: "" #ENTER THE USER ID. for when there is an error. empty = no ping.
    webhook_ping_role: "" #ENTER THE ROLE ID. for when there is an error. empty = no ping.

verbose: false # loads of more logs?